from __future__ import annotations

from collections.abc import AsyncIterator, Sequence
from typing import Any, Protocol

from protocol.generated.python import (
    AdapterDescriptor,
    AdapterHealth,
    AdapterStreamEnd,
    AgentResult,
    AgentSessionHandle,
    AgentTaskSpec,
    ApprovalDispatch,
    ApprovalView,
    CancelRequest,
    CancelResult,
    HubEvent,
    ResumeRequest,
    SessionView,
)

from .domain import AgentCandidate, RuntimeEventDraft


class AgentAdapterPort(Protocol):
    async def detect(self) -> AdapterDescriptor: ...
    async def health(self) -> AdapterHealth: ...
    async def start(self, spec: AgentTaskSpec) -> AgentSessionHandle: ...
    async def resume(self, request: ResumeRequest) -> None: ...
    def stream_events(self, session_id: str) -> AsyncIterator[HubEvent | AdapterStreamEnd]: ...
    async def approve(self, dispatch: ApprovalDispatch) -> None: ...
    async def cancel(self, request: CancelRequest) -> CancelResult: ...
    async def collect_result(self, session_id: str) -> AgentResult: ...


class AdapterDirectoryPort(Protocol):
    async def list_candidates(self) -> Sequence[AgentCandidate]: ...
    def adapter_for(self, agent_instance_id: str) -> AgentAdapterPort: ...


class RuntimeEventSink(Protocol):
    async def append(self, draft: RuntimeEventDraft) -> HubEvent | None: ...
    async def load_task_events(self, task_id: str, after_seq: int = 0) -> Sequence[HubEvent]: ...


class SessionRepositoryPort(Protocol):
    async def get(self, session_id: str) -> SessionView | None: ...
    async def save(self, session: SessionView) -> None: ...
    async def list(self, query: dict[str, Any]) -> Sequence[SessionView]: ...


class ApprovalRepositoryPort(Protocol):
    async def get(self, approval_id: str) -> ApprovalView | None: ...
    async def save(self, approval: ApprovalView) -> None: ...
    async def list(self, query: dict[str, Any]) -> Sequence[ApprovalView]: ...
